### ISSUE TITLE
Registry Review 0.4.0

### ISSUE THREAD

**Issue by ngokevin** [takahirox/aframe-outline#5]
- [x] Can the description in GitHub + package.json + README be more specific? Like "Outline post-processing effect component for A-Frame."
- [x] Is it possible to support the `remove()` method? If I remove the `outline` attribute, can we remove the effect?
- [x] I don't think we need to handle the `play()` method. `.play()` gets called after update, and there's no need to do anything on scene resume. https://github.com/takahirox/aframe-outline/blob/master/index.js#L27
- [x] Can we crop the browser chrome out of the screenshot?
- [x] README mentions `aframe-deferred-renderer`
- [x] Add a small note in the README to attach the component to the scene element in How to Use

**Comment by takahirox** [comment]
Done
